const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.video,
		C3.Behaviors.Fade,
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Behaviors.Flash,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.video.Cnds.IsPlaying,
		C3.Plugins.video.Acts.SetPlaybackRate,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.video.Exps.PlaybackTime,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.video.Acts.Pause,
		C3.Plugins.video.Acts.SetPlaybackTime,
		C3.Plugins.video.Acts.SetMuted,
		C3.Plugins.video.Acts.SetVolume,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.video.Cnds.OnPlaybackEvent,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.video.Acts.SetSource2,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Touch.Exps.X,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.System.Exps.log10,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Mouse.Cnds.OnMovement,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{naStop: 0},
	{naStart: 0},
	{mgStop: 0},
	{mgStart: 0},
	{Fade: 0},
	{Video: 0},
	{posX: 0},
	{posY: 0},
	{DragDrop: 0},
	{Tween: 0},
	{naBtn: 0},
	{mgBtn: 0},
	{dragArea: 0},
	{isFill: 0},
	{dragPlaceItem: 0},
	{dragItem: 0},
	{Flash: 0},
	{hand: 0},
	{Browser: 0},
	{switchBox: 0},
	{isDark: 0},
	{switchBtn: 0},
	{Touch: 0},
	{fullScreenBtn: 0},
	{shareBtn: 0},
	{audioBtn: 0},
	{refreshBtn: 0},
	{Audio: 0},
	{loadingText: 0},
	{playerBarBg: 0},
	{videoSoundBtn: 0},
	{videoPlayBtn: 0},
	{Mouse: 0},
	{beforeTime: 0},
	{videoIndex: 0},
	{resetFlagIndex: 0},
	{title: 0},
	{shortCut: 0},
	{fullBtn: 0},
	{speedBtn: 0},
	{isActive: 0},
	{value: 0},
	{speedBox: 0},
	{Text: 0},
	{videoPlayerBarBg: 0},
	{videoPlayerBarToggle: 0},
	{videoPlayerBarFill: 0},
	{soundBarBg: 0},
	{soundBarToggle: 0},
	{soundBarFill: 0},
	{videoTime: 0},
	{flagIndex: 0},
	{flag: 0},
	{prevBtn: 0},
	{nextBtn: 0},
	{timeText: 0},
	{timeText2: 0},
	{timeText3: 0},
	{videoTitle: 0},
	{nextFlagBtn: 0},
	{prevFlagBtn: 0},
	{switch: 0},
	{switchLamb: 0},
	{loaderEmpty: 0},
	{loaderFill: 0},
	{loaderLogo: 0},
	{orbitalLogo: 0},
	{bg: 0},
	{videoSpeed: 0},
	{currentVideoTime: 0},
	{totalVideoTime: 0},
	{beforeVideoTime: 0},
	{activeVideoIndex: 0},
	{activeFlagIndex: 0},
	{mouseIdleTimer: 0},
	{localVideoIndex: 0},
	{Index: 0},
	{isLoader: 0}
];

self.InstanceType = {
	Video: class extends self.IWorldInstance {},
	naBtn: class extends self.ISpriteInstance {},
	mgBtn: class extends self.ISpriteInstance {},
	dragArea: class extends self.ISpriteInstance {},
	dragPlaceItem: class extends self.ISpriteInstance {},
	dragItem: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	switchBox: class extends self.ISpriteInstance {},
	switchBtn: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	fullScreenBtn: class extends self.ISpriteInstance {},
	shareBtn: class extends self.ISpriteInstance {},
	audioBtn: class extends self.ISpriteInstance {},
	refreshBtn: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	loadingText: class extends self.ITextInstance {},
	playerBarBg: class extends self.ISpriteInstance {},
	videoSoundBtn: class extends self.ISpriteInstance {},
	videoPlayBtn: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	shortCut: class extends self.ISpriteInstance {},
	fullBtn: class extends self.ISpriteInstance {},
	speedBtn: class extends self.ISpriteInstance {},
	speedBox: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	videoPlayerBarBg: class extends self.ISpriteInstance {},
	videoPlayerBarToggle: class extends self.ISpriteInstance {},
	videoPlayerBarFill: class extends self.ISpriteInstance {},
	soundBarBg: class extends self.ISpriteInstance {},
	soundBarToggle: class extends self.ISpriteInstance {},
	soundBarFill: class extends self.ISpriteInstance {},
	flag: class extends self.ISpriteInstance {},
	prevBtn: class extends self.ISpriteInstance {},
	nextBtn: class extends self.ISpriteInstance {},
	timeText: class extends self.ITextInstance {},
	timeText2: class extends self.ITextInstance {},
	timeText3: class extends self.ITextInstance {},
	videoTitle: class extends self.ITextInstance {},
	nextFlagBtn: class extends self.ISpriteInstance {},
	prevFlagBtn: class extends self.ISpriteInstance {},
	switch: class extends self.ISpriteInstance {},
	switchLamb: class extends self.ISpriteInstance {},
	loaderEmpty: class extends self.ISpriteInstance {},
	loaderFill: class extends self.ISpriteInstance {},
	loaderLogo: class extends self.ISpriteInstance {},
	orbitalLogo: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {}
}